var e=qSel(".pTtl > span"),t=new Date,months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],formattedDate=` - Today <span style="font-size: 18px;">(${months[t.getMonth()]} ${t.getDate()}, ${t.getFullYear()})</span>`;e.innerHTML=e.innerHTML+formattedDate;
function handleQueryResponse(e){if(e.isError()){console.error("Error in query: "+e.getMessage()+" "+e.getDetailedMessage());return}var t=e.getDataTable(),r=document.getElementById("dataTable");r.innerHTML="";for(var a=r.createTHead().insertRow(0),n=0;n<t.getNumberOfColumns();n++){var o=document.createElement("th");o.textContent=t.getValue(0,n),a.appendChild(o)}for(var l=1;l<t.getNumberOfRows();l++)for(var s=r.insertRow(-1),g=0;g<t.getNumberOfColumns();g++)s.insertCell(g).textContent=t.getFormattedValue(l,g);addArrowsToColumn3(r),addLinksToTable(r),updatePetrolPrice(),drawTable2()}
function handleQueryResponse2(e){if(e.isError()){console.log("Error in query: "+e.getMessage()+" "+e.getDetailedMessage());return}for(var t=e.getDataTable(),r="<tr>",a=0;a<t.getNumberOfColumns();a++)r+="<th>"+t.getColumnLabel(a)+"</th>";r+="</tr>";for(var o=0;o<t.getNumberOfRows();o++){r+="<tr>",r+="<td>"+new Date(t.getValue(o,0)).toLocaleString("default",{month:"short",year:"numeric"})+"</td>";for(var n=1;n<t.getNumberOfColumns();n++)r+="<td>"+t.getValue(o,n)+"</td>";r+="</tr>"}document.getElementById("table2Body").innerHTML=r,addArrowsToSecondTable()}
function addArrowsToSecondTable(){var e=document.getElementById("dataTable2");for(var t=1;t<e.rows.length;t++){var n=e.rows[t].cells[1],r=e.rows[t].cells[2],a=n.textContent.trim(),o=r.textContent.trim(),l=extractValue(a),c=extractValue(o),s=getArrow(l),u=getArrow(c);n.innerHTML=formatCellContent(a,s),r.innerHTML=formatCellContent(o,u)}}function extractValue(e){var t=e.match(/\(([^)]+)\)/);return t&&t.length>1?parseFloat(t[1].trim()):0}function getArrow(e){return e>0?`<span style="color: red;">\u25B2</span>`:e<0?`<span style="color: green;">\u25BC</span>`:`\u25FC`}function formatCellContent(e,t){var n=e.match(/\(([^)]+)\)/)[1];return e.replace(/\(([^)]+)\)/,`(${n}${t})`)}
addArrowsToSecondTable();
function addLinksToTable(e,t){for(var n=1;n<e.rows.length;n++){var r=e.rows[n].cells[0],a=r.textContent.trim();if(t.hasOwnProperty(a)){var o=document.createElement("a");o.href=t[a],o.textContent=a,r.innerHTML="",r.appendChild(o)}}}
function addLinksToTable(e,t){for(var n=1;n<e.rows.length;n++){var r=e.rows[n].cells[0],a=r.textContent.trim();if(t.hasOwnProperty(a)){var o=document.createElement("a");o.href=t[a],o.textContent=a,r.innerHTML="",r.appendChild(o)}}}
function addArrowsToColumn3(e){for(var t=1;t<e.rows.length;t++){var n=e.rows[t].cells[2],r=n.textContent.trim(),a=r.match(/(-?[\d,]+\.*\d*)/);if(a&&a.length>0){var l=parseFloat(a[0].replace(",","").trim()),o=document.createElement("span");o.classList.add("arrow"),isNaN(l)||(l>0?(o.textContent='\u25B2',o.style.color="red"):l<0?(o.textContent='\u25BC',o.style.color="green"):(o.textContent='\u25FC',o.style.fontWeight="bold"));var d=document.createElement("span");d.textContent=a[0];var p=document.createElement("span");p.textContent=r.replace(a[0],""),n.innerHTML="",n.appendChild(p),n.appendChild(d),n.appendChild(document.createTextNode(" ")),n.appendChild(o)}}}
function addLinksToTable(e){for(var t={},n=1;n<e.rows.length;n++){var r=e.rows[n].cells[0],a=r.textContent.trim();if(t.hasOwnProperty(a)){var o=document.createElement("a");o.href=t[a],o.textContent=a,r.innerHTML="",r.appendChild(o)}}}
