var e=qSel(".pTtl > span"),t=new Date,months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],formattedDate=` - Today <span style="font-size: 18px;">(${months[t.getMonth()]} ${t.getDate()}, ${t.getFullYear()})</span>`;e.innerHTML=e.innerHTML+formattedDate;
function handleQueryResponse(e){if(e.isError()){console.error("Error in query: "+e.getMessage()+" "+e.getDetailedMessage());return}for(var t=e.getDataTable(),r=document.getElementById("dataTable"),a=r.createTHead().insertRow(0),n=0;n<t.getNumberOfColumns();n++){var o=document.createElement("th");o.textContent=t.getColumnLabel(n),a.appendChild(o)}for(var l=document.createElement("tbody"),n=0;n<t.getNumberOfRows();n++)for(var s=l.insertRow(n),d=0;d<t.getNumberOfColumns();d++)s.insertCell(d).textContent=t.getFormattedValue(n,d);r.appendChild(l),addArrowsToColumn3(r),addLinksToTable(r),updatePetrolPrice(),drawTable2()}
function handleQueryResponse2(e){if(e.isError()){console.log("Error in query: "+e.getMessage()+" "+e.getDetailedMessage());return}for(var t=e.getDataTable(),r="<tr>",a=0;a<t.getNumberOfColumns();a++)r+="<th>"+t.getColumnLabel(a)+"</th>";r+="</tr>";for(var o=0;o<t.getNumberOfRows();o++){r+="<tr>",r+="<td>"+new Date(t.getValue(o,0)).toLocaleString("default",{month:"short",year:"numeric"})+"</td>";for(var n=1;n<t.getNumberOfColumns();n++)r+="<td>"+t.getValue(o,n)+"</td>";r+="</tr>"}document.getElementById("table2Body").innerHTML=r,addArrowsToSecondTable()}
function addArrowsToSecondTable(){for(var t=document.getElementById("dataTable2"),e=1;e<t.rows.length;e++){var r=t.rows[e].cells[1],n=t.rows[e].cells[2],o=r.textContent.trim(),a=n.textContent.trim(),l=extractValue(o),c=extractValue(a),s=getArrow(l),u=getArrow(c);r.innerHTML=formatCellContent(o,s),n.innerHTML=formatCellContent(a,u)}}function extractValue(t){var e=t.match(/\(([^)]+)\)/);return e&&e.length>1?parseFloat(e[1].trim()):0}function getArrow(t){return t>0?'<span style="color: red;">\u25B2</span>':t<0?'<span style="color: green;">\u25BC</span>':"\u25FC"}function formatCellContent(t,e){var r=t.match(/\(([^)]+)\)/)[1];return t.replace(/\(([^)]+)\)/,`(${r}${e})`)}
addArrowsToSecondTable();
function addLinksToTable(e,t){for(var n=1;n<e.rows.length;n++){var r=e.rows[n].cells[0],a=r.textContent.trim();if(t.hasOwnProperty(a)){var o=document.createElement("a");o.href=t[a],o.textContent=a,r.innerHTML="",r.appendChild(o)}}}
function addLinksToTable(e,t){for(var n=1;n<e.rows.length;n++){var r=e.rows[n].cells[0],a=r.textContent.trim();if(t.hasOwnProperty(a)){var o=document.createElement("a");o.href=t[a],o.textContent=a,r.innerHTML="",r.appendChild(o)}}}
function addArrowsToColumn3(e){for(var t=1;t<e.rows.length;t++){var n=e.rows[t].cells[2],r=n.textContent.trim(),a=r.match(/(-?[\d,]+\.*\d*)/);if(a&&a.length>0){var l=parseFloat(a[0].replace(",","").trim()),o=document.createElement("span");o.classList.add("arrow"),isNaN(l)||(l>0?(o.textContent='\u25B2',o.style.color="red"):l<0?(o.textContent='\u25BC',o.style.color="green"):(o.textContent='\u25FC',o.style.fontWeight="bold"));var d=document.createElement("span");d.textContent=a[0];var p=document.createElement("span");p.textContent=r.replace(a[0],""),n.innerHTML="",n.appendChild(p),n.appendChild(d),n.appendChild(document.createTextNode(" ")),n.appendChild(o)}}}
function addLinksToTable(e){for(var t={},n=1;n<e.rows.length;n++){var r=e.rows[n].cells[0],a=r.textContent.trim();if(t.hasOwnProperty(a)){var o=document.createElement("a");o.href=t[a],o.textContent=a,r.innerHTML="",r.appendChild(o)}}}
